parameters: {}
environment: {}
packages:
    - name: sample
      shared: false
      environment: {}
      parameters: {}
      annotations: {}
      functions:
        - name: hello
          binary: false
          main: ""
          runtime: python:default
          triggers:
          - name: trig
            sourceType: scheduler
            sourceDetails:
              cron: '*/15 * * * *'
